"""Time Series Semantics (TSS) alignment module.

Establishes an informatics mapping between multivariate features from RFE
and the underlying physical drivers of market volatility. Uses causally-guided
attention and unsupervised semantic labeling.

Semantic labels are generated by extracting context feature vectors from
significant price fluctuations (at IDP positions) via the causality-guided
attention mechanism. K-Means clusters these high-dimensional volatility
features, then post-hoc physical validation assigns interpretable labels
by examining cluster-center values on specific physically-meaningful dimensions.

"""

import torch
import torch.nn as nn
import numpy as np
from .causal_attention import CausalBiasAttention


class TSSModule(nn.Module):
    """Time Series Semantics alignment module.

    Args:
        d_feat: feature dimension D' (from RFE, typically 5 * enc_in)
        n_heads: number of attention heads
        dropout: dropout rate for attention
        n_clusters: number of K-Means clusters
    """

    # Pre-defined semantic labels (mapped by physically-meaningful dimensions)
    SEMANTIC_LABELS = [
        'Demand Surge',
        'Renewable Oversupply',
        'Fossil Oversupply',
        'High Volatility',
        'Low Demand/Stable',
    ]

    def __init__(self, d_feat: int, n_heads: int = 8, dropout: float = 0.1,
                 n_clusters: int = 5):
        super().__init__()
        self.d_feat = d_feat
        self.n_clusters = n_clusters
        self.enc_in = d_feat // 5  # number of original input variables

        # Causal-bias attention
        self.causal_attn = CausalBiasAttention(
            d_model=d_feat, n_heads=n_heads, dropout=dropout
        )

        # Cluster centers (set via fit_clusters)
        self.register_buffer('cluster_centers', None)
        # Causal matrix (set via set_causal_matrix)
        self.register_buffer('causal_matrix', torch.eye(d_feat))

        # Semantic label mapping: cluster_id -> label string
        self.label_map = {}

    def set_causal_matrix(self, C: torch.Tensor):
        """Set the causal matrix (call once after Granger precompute)."""
        self.register_buffer('causal_matrix', C.float())

    def fit_clusters(self, m_attn_pool: torch.Tensor):
        """Fit K-Means clusters on context vectors from significant price
        fluctuation positions.

        Each row of m_attn_pool is a D'-dimensional context vector extracted
        at a position where the price variable exhibits significant fluctuation
        (i.e., at IDP locations on the price channel).

        Args:
            m_attn_pool: [total_contexts, D'] context feature vectors
        """
        if m_attn_pool.shape[0] < self.n_clusters:
            return

        try:
            from sklearn.cluster import KMeans
        except ImportError:
            print("[WARNING] sklearn not available; skipping cluster fitting.")
            return

        data = m_attn_pool.detach().cpu().numpy()
        kmeans = KMeans(n_clusters=self.n_clusters, random_state=42, n_init=10)
        kmeans.fit(data)

        centers = torch.from_numpy(kmeans.cluster_centers_).float()  # [K, D']
        self.register_buffer('cluster_centers', centers)

        # Assign semantic labels by examining physically-meaningful dimensions
        self._assign_labels(centers)

    def _assign_labels(self, centers: torch.Tensor):
        """Assign interpretable semantic labels to each cluster by examining
        cluster-center values on specific physically-relevant feature dimensions.

        """
        K, D = centers.shape
        V = self.enc_in  # number of variables (13)

        # Feature offsets within the 65-dim vector
        T_OFFSET = 0       # trend features start at dim 0
        M_OFFSET = V       # magnitude features start at dim 13
        # D_OFFSET = 2*V   # duration at dim 26
        # S_OFFSET = 3*V   # slope at dim 39
        # A_OFFSET = 4*V   # area at dim 52

        # Physically meaningful dimension indices
        idx_fossil_gen = 7
        idx_renewable_gen = 8
        idx_total_demand = 10
        idx_real_time_price = 12

        # Per-cluster physical scores
        demand_score = centers[:, T_OFFSET + idx_total_demand]       # trend of total demand
        renewable_score = centers[:, T_OFFSET + idx_renewable_gen]    # trend of renewable gen
        fossil_score = centers[:, T_OFFSET + idx_fossil_gen]          # trend of fossil gen
        volatility_score = centers[:, M_OFFSET + idx_real_time_price] # magnitude of price

        # Rank clusters by each score (descending: higher = more characteristic)
        demand_rank = demand_score.argsort(descending=True)
        renewable_rank = renewable_score.argsort(descending=True)
        fossil_rank = fossil_score.argsort(descending=True)
        volatility_rank = volatility_score.argsort(descending=True)
        # Also ascending rank for "Low Demand/Stable"
        demand_rank_asc = demand_score.argsort(descending=False)

        # Assign labels greedily (each cluster gets exactly one label)
        assigned = set()
        labels = {}

        def _assign(k, label):
            if k not in assigned:
                labels[k] = label
                assigned.add(k)
                return True
            return False

        # Priority order: the 3 core EPF labels first, then volatility, then low demand
        for k in demand_rank:
            if _assign(k.item(), 'Demand Surge'):
                break
        for k in renewable_rank:
            if _assign(k.item(), 'Renewable Oversupply'):
                break
        for k in fossil_rank:
            if _assign(k.item(), 'Fossil Oversupply'):
                break
        for k in volatility_rank:
            if _assign(k.item(), 'High Volatility'):
                break
        for k in demand_rank_asc:
            if _assign(k.item(), 'Low Demand/Stable'):
                break

        # Fallback: any remaining unassigned clusters get a generic label
        for k in range(K):
            if k not in assigned:
                labels[k] = f'Pattern_{k}'

        self.label_map = labels

        # Print post-hoc validation info
        for k in range(K):
            d_s = demand_score[k].item()
            r_s = renewable_score[k].item()
            f_s = fossil_score[k].item()
            v_s = volatility_score[k].item()
            print(f"  Cluster {k} '{labels[k]}': "
                  f"demand_trend={d_s:+.3f} renewable_trend={r_s:+.3f} "
                  f"fossil_trend={f_s:+.3f} price_magnitude={v_s:.3f}")

    def assign_patch_labels(self, m_feat: torch.Tensor,
                            patch_boundaries: list) -> list:
        """Assign semantic labels to each patch.

        Args:
            m_feat: [B, L, D'] attention-refined features
            patch_boundaries: list of (start, end) indices for each patch

        Returns:
            patch_labels: list of lists, shape [B, N] of label strings
        """
        if self.cluster_centers is None:
            return [[''] * len(patch_boundaries) for _ in range(m_feat.shape[0])]

        B = m_feat.shape[0]
        centers = self.cluster_centers  # [K, D']
        all_labels = []

        for b in range(B):
            batch_labels = []
            for start, end in patch_boundaries:
                # Mean-pool features within the patch
                patch_vec = m_feat[b, start:end, :].mean(dim=0)  # [D']

                # Find nearest cluster center
                dists = torch.norm(centers - patch_vec.unsqueeze(0), dim=1)
                nearest = dists.argmin().item()

                batch_labels.append(self.label_map.get(nearest, f'Pattern_{nearest}'))
            all_labels.append(batch_labels)

        return all_labels

    def forward(self, m_feat: torch.Tensor) -> torch.Tensor:
        """Apply causal-bias attention to refine features.

        Args:
            m_feat: [B, L, D'] feature matrix from RFE

        Returns:
            m_attn: [B, L, D'] causally-refined feature representation
        """
        return self.causal_attn(m_feat, self.causal_matrix)
